
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hello-spring-cloud
  description: Spring boot project
  annotations:
    argocd/app-name: -dev
    backstage.io/kubernetes-id: hello-spring-cloud
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-local-arun/hello-spring-cloud
  links:
    - url: https://devspaces/#https://github.com/rhdh-local-arun/hello-spring-cloud
      title: OpenShift Dev Spaces (VS Code editor)
      icon: web
spec:
  type: service
  system: system:default/rhdh-local
  lifecycle: production
  owner: user:default/arunhari82
