
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hello-spring-cloud
  description: Spring boot project
  annotations:
    tektonci/build-namespace: hello-spring-cloud-dev
    janus-idp.io/tekton: hello-spring-cloud
    argocd/app-selector: rht-gitops.com/janus-argocd=hello-spring-cloud-bootstrap
    backstage.io/kubernetes-id: hello-spring-cloud
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-local-arun/hello-spring-cloud
    quay.io/repository-slug: quayadmin/hello-spring-cloud
  links:
    - url: https://devspaces.apps.cluster-q82c9.q82c9.sandbox3038.opentlc.com/#https://github.com/rhdh-local-arun/hello-spring-cloud
      title: OpenShift Dev Spaces (VS Code editor)
      icon: web           
    - url: https://hello-spring-cloud-hello-spring-cloud-dev.apps.cluster-q82c9.q82c9.sandbox3038.opentlc.com/actuator
      title: Application
      icon: web  
spec:
  type: service
  system: system:default/finance_system
  lifecycle: production
  owner: user:default/arunhari82
