
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hello-spring-cloud
  description: cf project
  annotations:
    tektonci/build-namespace: hello-spring-cloud-dev
    janus-idp.io/tekton: hello-spring-cloud
    argocd/app-name: my-springboot-app-dev
    backstage.io/kubernetes-id: hello-spring-cloud
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-local-arun/hello-spring-cloud
    quay.io/repository-slug: anattama/my-springboot-app
  links:
    - url: https://devspaces.apps.cluster-6kknq.6kknq.sandbox63.opentlc.com/#https://github.com/rhdh-local-arun/hello-spring-cloud
      title: OpenShift Dev Spaces (VS Code editor)
      icon: web
spec:
  type: service
  system: system:default/rhdh-local
  lifecycle: production
  owner: user:default/arunhari82
